name: Generate Changelog manually
on:
  workflow_dispatch:

jobs:
  changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: "✏️ Generate release changelog"
        id: changes
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 
          output: 
      - run: |
          echo '${{ steps.changes.outputs.changelog }}'
          cat CHANGELOG.md
          git config user.name "Peter Jaeckel" 
          git config user.email "peter@hapetech.de"
          git add CHANGELOG.md
          git status
          git commit --amend --no-edit
          git push origin
